version: '3.8'

services:
  postgres-test-db:
    image: postgres:latest
    container_name: postgres-test-db
    environment:
      POSTGRES_USER: DbTestUser
      POSTGRES_PASSWORD: 1Strong_Password!
      POSTGRES_DB: HealthDevice_Test
    ports:
      - "5433:5432" # Map port 5433 on the host to 5432 in the container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      postgres-test-db:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres-test-db;Port=5432;Database=HealthDevice_Test;Username=postgres;Password=yourpassword"